### PR TITLE
Require the bugsnag top level lib when notifying of a deploy

### LINKED ISSUE #274: Bugnsag deploy notification failed, #<NoMethodError: undefined method `configuration' for Bugsnag:Module>
Hi Bugsnag,

Thanks for your work, we are trying to integrate the Capistrano hook with : 

```ruby
require 'bugsnag/capistrano'
set :bugsnag_api_key, 'API-KEY'
```
It doesn't seem to work, we got the error : 

```
Bugnsag deploy notification failed, #<NoMethodError: undefined method `configuration' for Bugsnag:Module>
```

We use capistrano (2.15.5) and bugsnag (3.0.0).

### PR DESCRIPTION
**Pull request by snmaynard**
This fixes #274 and #272.

### CODE REVIEW

**Comment by kattrali** [comment]
:star2:

**Comment by flynfish** [comment]
Is this going to be released in a gem update soon?

**Comment by kattrali** [comment]
@flynfish Yep! Released in [4.0.0](https://github.com/bugsnag/bugsnag-ruby/blob/master/CHANGELOG.md#400-9-mar-2016), (its a major release since support for ruby 1.8 was dropped).

**Comment by flynfish** [comment]
:+1: thanks!

**Pull request merged**
