### PR TITLE
Add gem version and SemVer compatibility badges to README

### PR DESCRIPTION
**Pull request by greysteil**
## Goal

Make it easier for new users to add `bugsnag` to their Gemfile.

## Design

Badges that show the version and how SemVer compatible this gem is (very) give users all the information they need to pick the right gem requirement.

This PR adds a version number and SemVer compatibility badge. Data comes from Dependabot (disclosure: I built it).

Here's what the badges look like:

Gem Version [SemVer](https://dependabot.com/compatibility-score.html?dependency-name=bugsnag&package-manager=bundler&version-scheme=semver)

## Review

For the submitter, initial self-review:

- [ ] Commented on code changes inline explain the reasoning behind the approach
- [ ] Reviewed the test cases added for completeness and possible points for discussion
- [ ] A changelog entry was added for the goal of this pull request
- [ ] Check the scope of the changeset - is everything in the diff required for the pull request?
- This pull request is ready for:
  - [ ] Initial review of the intended approach, not yet feature complete
  - [ ] Structural review of the classes, functions, and properties modified
  - [ ] Final review

For the pull request reviewer(s), this changeset has been reviewed for:

- [ ] Consistency across platforms for structures or concepts added or modified
- [ ] Consistency between the changeset and the goal stated above
- [ ] Internal consistency with the rest of the library - is there any overlap between existing interfaces and any which have been added?
- [ ] Usage friction - is the proposed change in usage cumbersome or complicated?
- [ ] Performance and complexity - are there any cases of unexpected O(n^3) when iterating, recursing, flat mapping, etc?
- [ ] Concurrency concerns - if components are accessed asynchronously, what issues will arise
- [ ] Thoroughness of added tests and any missing edge cases
- [ ] Idiomatic use of the language

### CODE REVIEW

**Comment by greysteil** [comment]
Yep - the idea here is to test SemVer by checking whether updates to bugsnag cause test failures for your users. The "score" is just the percentage of CI runs that pass when updating between SemVer compatible versions, but it still gives a pretty clear indicator that bugsnag updates won't require code changes for your users if/when the upgrade it.

There are some difficulties with flaky tests that I haven't 100% ironed out yet (I should be able to filter out flaky test suites based on all the other updates Dependabot is doing for that repo) but in practice it seems flaky tests only affect the score very slightly. Of the 163 updates Dependabot has done of bugsnag only 3 have ever "caused" test failures.

**Comment by snmaynard** [comment]
Yeah - I just don't think that a 98% score is particularly clear to people who don't know what it is and how it works. I think that we'll likely get confused users if we merge this. Maybe you could give a grading system instead, but as it is I dont think it's clearer than us saying we use semver versioning.

**Comment by greysteil** [comment]
👍, although sorry to hear that. I've renamed the badge to be "semver stability" to make it clearer what it does, and I'm going to try to filter out the flaky specs later today / tomorrow.

Keep up the great work with Bugsnag! ❤️

**Comment by snmaynard** [comment]
You could do something like 95%+ is given an excellent rating?

**Comment by snmaynard** [comment]
Yeah fair - do you have examples of other projects that use it?

**Comment by greysteil** [comment]
I only created it a few days, but [jest](https://github.com/facebook/jest#jest) have added it, [sentry](https://github.com/getsentry/raven-ruby/#raven-ruby-the-ruby-client-for-sentry) have, [capybara](https://github.com/teamcapybara/capybara#capybara), [oj](https://github.com/ohler55/oj#-gem), and [rubocop](https://github.com/rubocop-hq/rubocop) (in prep for going 1.0.0 in the next few weeks). Think there's a couple of others, too.

**Comment by snmaynard** [comment]
I'll reopen it and see what @kattrali thinks when she is back from pto next week - thanks for all the context!

**Comment by greysteil** [comment]
@kattrali - any thoughts? The folks at Webpack asked for a version that only displayed updates to the latest version, so there's this option now, too:

[SemVer](https://dependabot.com/compatibility-score.html?dependency-name=bugsnag&package-manager=bundler&version-scheme=semver&new-version=latest)

**Comment by kattrali** [comment]
This is pretty cool! The context discussion helps too, so thanks @greysteil, @snmaynard.

**Pull request merged**
