### PR TITLE
Added configuration option to disable autoconfiguration

### LINKED ISSUE #391: Difficulty configuring Bugsnag in Rails before it configures itself
Here's an example initializer in Rails:

``` ruby
# config/initializers/bugsnag.rb
puts "Bugsnag initializer reached"
Bugsnag.configure do |config|
  config.logger = Logger.new("/dev/null")
  config.api_key = ENV.fetch("BUGSNAG_API_KEY")
end
```

The Bugsnag ready message gets logged before this initializer runs:

```
$ rails c
** [Bugsnag] Bugsnag exception handler 5.5.0 ready
Bugsnag initializer reached
Loading development environment (Rails 5.1.4)
```

I want to change the Bugsnag logger and/or explicitly configure Bugsnag myself. I do not want the gem to try to automatically detect its own configuration. What is the correct way to do this in Rails and other Ruby environments when using Gemfiles/Rubygems to load this gem?

### PR DESCRIPTION
**Pull request by Cawllec**
This adds two functions, `load_integrations` & `load_integration(integration)` that allow Bugsnag integrations to be loaded during runtime.

By default, `load_integrations` will be run when the `bugsnag` module is required.  This behaviour can be disabled using the environment variable `BUGSNAG_DISABLE_AUTOCONFIGURE`.

Tentatively fixes #391, #403

### CODE REVIEW

**Comment by snmaynard** [comment]
What manual testing has been done?

**Comment by Cawllec** [comment]
I've tested it in rails to ensure the environment variable stops it from loading the railtie, which works correctly.  I guess the main issue would be that it still loads in `bugsnag\integrations\rake` regardless of environment variables as it's always done that separately to the other integrations.

**Comment by snmaynard** [comment]
We should test it for all the integrations to ensure that manually loading the sidekiq integration (as an example) works and we dont need to make any changes to support the later loading.

**Comment by Cawllec** [comment]
Now tested and confirmed to work with:
- Sidekiq
- Rails
- Resque

Does not work with:
- Rack

**Comment by kattrali** [comment]
Rack or rake? Checking because rake was mentioned in https://github.com/bugsnag/bugsnag-ruby/pull/419#issuecomment-360204887

**Comment by Cawllec** [comment]
Rack.  We loaded the Rack integration outside of the `load_integrations` loop previously, probably means removing it from there would make this a breaking change.

**Comment by kattrali** [comment]
What broke when moving the import to the `load_integrations` loop?

**Comment by Cawllec** [comment]
Nothing I suppose.  I haven't added it to the loop yet (as it was separate anyway), but it shouldn't change the expected behaviour if I do.  I'll do that and test it.

**Comment by Cawllec** [comment]
Everything works as expected with rack, and there's no magic conf happening.

**Pull request merged**
