### PR TITLE
Give precedence to the BUGSNAG_RELEASE_STAGE environment variable

### PR DESCRIPTION
**Pull request by s-andringa**
Implements #298

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
This is technically a breaking change, right?

**Comment by s-andringa** [comment]
Yes, if people have `BUGSNAG_RELEASE_STAGE` set to something different than the Rails/Rack env the behaviour changes.

**Comment by kattrali** [comment]
Thank you for the contribution, @s-andringa. Changing this override behavior makes sense, as any Rails/Rack user who attempting to override `BUGSNAG_RELEASE_STAGE` had no effect. This change is only breaking in the sense that now the environment variable would do something.

**Comment by snmaynard** [comment]
This seems good to me too - merging down now

**Comment by snmaynard** [comment]
Thanks @s-andringa!

**Pull request merged**
