### PR TITLE
Rake task to add a heroku deploy hook

### PR DESCRIPTION
**Pull request by loopj**

### CODE REVIEW

**Comment by ConradIrwin** [comment]
@loopj what's the status of getting the event-server to support this?

**Comment by loopj** [comment]
I actually merged https://github.com/bugsnag/bugsnag-event-server/pull/24 but never fully tested it.

**Comment by snmaynard** [comment]
was it ever deployed?

**Comment by loopj** [comment]
Yes, I think I deployed it but not 100% sure since it was a while ago

On Fri, Jan 2, 2015 at 3:38 PM, Simon Maynard <notifications@github.com>
wrote:

> was it ever deployed?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bugsnag/bugsnag-ruby/pull/167#issuecomment-68573387>.
>



-- 
James Smith
Bugsnag <https://bugsnag.com> Co-founder & CEO

loopj.com | @loopj <https://twitter.com/loopj> | github.com/loopj

**Comment by loopj** [comment]
This is ready for review/merge. This has been tesed with production event-server and a couple of Heroku apps.

We'll also need to merge https://github.com/bugsnag/bugsnag-notifier-api/pull/8 at the same time.

**Pull request merged**
