### PR TITLE
Updates to use sidekiq v3 error handling

### PR DESCRIPTION
**Pull request by Cawllec**
Ensures that an error handler is correctly assigned in newer versions of sidekiq.

While it has very basic sidekiq integration tests already, this is a prime candidate for the new integrations test runner, which I will be working with this week.

Manually tested in:

- [x] Sidekiq 2
- [x] Sidekiq 3

### CODE REVIEW

**Comment by snmaynard** [comment]
I would like to see integration tests for this, rather than just unit. Can we add some maze tests?

**Comment by javierjulio** [comment]
Will this address #417 too or is that being done in another PR?

**Comment by Cawllec** [comment]
That will be in a separate PR, as decisions about that change still have to be made.

**Comment by snmaynard** [comment]
I have reworked the approach here to give us the sidekiq queue information in all versions. I ran the maze tests and they all passed.

**Pull request merged**
